# Copyright (C) 2016 and later: Unicode, Inc. and others.
# License & terms of use: http://www.unicode.org/copyright.html
#
# GitHub Action configuration script for ICU continuous integration tasks.

name: GHA ICU4C Windows build

on:
  push:
    branches:
      - main
      - windows-build
    paths:
      - 'icu4c/**'
      - 'testdata/**'
      - '.github/workflows/**'
  pull_request:
    branches: '**'
    paths:
      - 'icu4c/**'
      - 'testdata/**'
      - '.github/workflows/**'
  workflow_dispatch:
    # To trigger the Env Test workflow manually, follow the instructions in
    # https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
    inputs:
      gitReleaseTag:
        description: 'Release tag to upload to. Must start with "release-"'
        type: string

# For non-release branches (namely: PRs), only run CI on the most recent commit. Cancel
# runs on previous commits mid-flight when new commits are pushed.
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-on-specific-branches
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'maint/') && github.ref != 'main' }}

permissions:
  contents: read

jobs:
  # Windows MSVC builds
  windows-msvc:
    runs-on: windows-2022  # Updated in BRS
    strategy:
      fail-fast: false
      matrix:
        include:
          - test_flags: 'x64 Debug'
            build_flags: '/p:Configuration=Debug /p:Platform=x64'
          - test_flags: 'x86 Debug'
            build_flags: '/p:Configuration=Debug /p:Platform=Win32'
          - test_flags: 'arm Release'
            build_flags: '/p:Configuration=Release /p:Platform=ARM'
          - test_flags: 'x64 Release'
            build_flags: '/p:LanguageStandard=stdcpplatest /p:Configuration=Release /p:Platform=x64'
          - test_flags: 'x64 Release'
            build_flags: '/p:_HAS_EXCEPTIONS=0 /p:Configuration=Release /p:Platform=x64'
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Build Solution x64
        if: contains(matrix.test_flags, 'arm Release')
        run: msbuild icu4c/source/allinone/allinone.sln /p:Configuration=Release /p:Platform=x64 /p:SkipUWP=true
      - name: Build Solution
        run: |
          msbuild icu4c/source/allinone/allinone.sln ${{ matrix.build_flags }} /p:SkipUWP=true
      - name: Run ${{ matrix.test_flags }} Tests (icucheck.bat)
        if: contains(matrix.test_flags, 'arm Release') == false
        run: |
          icu4c\source\allinone\icucheck.bat ${{ matrix.test_flags }}

  # Windows data filter build
  windows-msvc-datafilter:
    runs-on: windows-2022  # Updated in BRS
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: Set ICU_DATA_FILTER_FILE variable
      run: |
        $filterPath = "${{ github.workspace }}\.github\data-filter.json"
        echo "ICU_DATA_FILTER_FILE=$filterPath" >> $GITHUB_ENV
      shell: pwsh
    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: Build Solution with Data Filter
      run: msbuild icu4c/source/allinone/allinone.sln /p:Configuration=Release /p:Platform=x64 /p:SkipUWP=true

  # Windows MSVC distribution release
  windows-msvc-dist-release:
    runs-on: windows-2022  # Updated in BRS
    permissions:
      contents: write # So that we can upload to release
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: 'x64'
            plat: 'x64'
            win_ver: 'Win64'
          - arch: 'x86'
            plat: 'Win32'
            win_ver: 'Win32'
          - arch: 'arm64'
            plat: 'ARM64'
            win_ver: 'WinARM64'
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: Build Solution x64
      if: contains(matrix.win_ver, 'ARM64')
      run: msbuild icu4c/source/allinone/allinone.sln /p:Configuration=Release /p:Platform=x64 /p:SkipUWP=true
    - name: Build Solution
      run: msbuild icu4c/source/allinone/allinone.sln /p:Configuration=Release /p:Platform=${{ matrix.plat }} /p:SkipUWP=true
    - name: Run Tests (icucheck.bat)
      if: contains(matrix.win_ver, 'ARM64') == false
      run: icu4c/source/allinone/icucheck.bat ${{ matrix.arch }} Release
    - name: "Run PowerShell: Distrelease script (${{ matrix.arch }})"
      run: |
        cd ./icu4c/
        ./packaging/distrelease.ps1 -arch ${{ matrix.arch }}
      shell: pwsh
    - name: Extract ICU version and rename zip file
      id: set-zip-name
      run: |
        # Extract ICU version from icuver.txt
        $icuverContent = Get-Content icu4c\source\data\misc\icuver.txt
        $icuVersion = ($icuverContent -match 'ICUVersion{"(\d+\.\d+\.\d+\.\d+)"}')[0]
        $icuVersion -match '\{"(.*?)"\}' | Out-Null
        $icuVersion = $matches[1]
        $majorVersion = $icuVersion.Split('.')[0]
        $minorVersion = $icuVersion.Split('.')[1]
        # Determine the new file name based on the version
        if ($minorVersion -eq "0") {
          $newZipName = "icu4c-${majorVersion}rc-${{ matrix.win_ver }}-MSVC2022"
        } else {
          $newZipName = "icu4c-${majorVersion}_${minorVersion}-${{ matrix.win_ver }}-MSVC2022"
        }
        # Debugging: Print the new zip name
        Write-Host "New Zip Name: $newZipName"
        # Rename the existing zip file
        cd icu4c\source\dist\ && ls -l .
        Rename-Item -Path icu-windows.zip -NewName "${newZipName}.zip"
        echo $newZipName
        ls -l .
        echo "newZipName=$newZipName" | Out-File -FilePath $env:GITHUB_ENV -Append
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: icu4c.${{ matrix.win_ver }}.run_#${{ github.run_number }}
        path: icu4c/source/dist/${{ env.newZipName }}.zip
    - name: Upload to release
      if: ${{ inputs.gitReleaseTag && startsWith(inputs.gitReleaseTag, 'release-') }}
      run: |
        gh release upload ${{ inputs.gitReleaseTag }} icu4c/source/dist/${{ env.newZipName }}.zip --clobber
      env:
        GH_TOKEN: ${{ github.token }}


